set -g base-index 1
set -g allow-predictions on

set -g @tokyonight-show-powerline 'off'

# List of plugins
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-sensible'
set -g @plugin 'psmux-plugins/psmux-theme-tokyonight'
set -g @plugin 'psmux-plugins/psmux-vim-navigator'

# Initialize PPM (keep this line at the very bottom of .psmux.conf)
run '~/.psmux/plugins/ppm/ppm.ps1'
