{{ if or (eq .chezmoi.os "linux") (eq .chezmoi.os "darwin") }}
[".config/kitty/themes"]
  type = "archive"
  url = "https://github.com/kovidgoyal/kitty-themes/archive/master.tar.gz"
  stripComponents = 2
  include = ["*/themes/**"]

[".config/alacritty/themes"]
  type = "archive"
  url = "https://github.com/alacritty/alacritty-theme/archive/master.tar.gz"
  exact = true
  stripComponents = 2
  include = ["*/themes/**"]

[".config/lsd/colors.yaml"]
  type = "archive-file"
  url = "https://github.com/catppuccin/lsd/archive/main.tar.gz"
  path = "lsd-main/themes/catppuccin-mocha/colors.yaml"

[".config/scooter/themes"]
  type = "archive"
  url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
  stripComponents = 2
  include = ["*/themes/**"]
{{ end }}
[".config/lazygit/themes"]
  type = "archive"
  url = "https://github.com/catppuccin/lazygit/archive/main.tar.gz"
  stripComponents = 2
  include = ["*/themes-mergable/**"]
{{ if (eq .chezmoi.os "windows") }}
["AppData/Roaming/Code/User/settings.json"]
  type = "file"
  source = "dot_config/Code/User/settings.json"

["AppData/Roaming/Code/User/keybindings.json"]
  type = "file"
  source = "dot_config/Code/User/keybindings.json"
{{ end }}
