before_script: wezterm cli set-tab-title dotfiles
session_name: dotfiles
windows:
  - window_name: editor
    layout: main-horizontal
    options:
       main-pane-height: 80%
    panes:
      - nvim .
      -

