tap "amar1729/formulae"
tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jesseduffield/lazydocker"
brew "asdf"
brew "awscli"
brew "gnupg"
brew "mas"
brew "pass"
brew "pinentry-mac"
brew "zsh-completions"
brew "amar1729/formulae/browserpass"
brew "getantibody/tap/antibody"
brew "jesseduffield/lazydocker/lazydocker"
cask "docker"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "logitech-options"
cask "sourcetree"
cask "station"
cask "upwork"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vmware-fusion"
cask "zoomus"
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Remote Desktop", id: 1295203466
mas "Archiver", id: 619437121
mas "System Monitor", id: 423368786
mas "Xcode", id: 497799835
