---
# See https://www.nerdfonts.com/cheat-sheet for additional icons
filetype:
  dir:  # Default = 
  file:  # Default = 
  pipe: 󰈲 # Default = 󰈲
  socket: 󰆨 # Default = 󰆨
  executable:  # Default = 
  symlink-dir:  # Default = 
  symlink-file:  # Default = 
  device-char:  # Default = 
  device-block: 󰜫 # Default = 󰜫
  special:  # Default = 

name:
  a:  # Default = 
  api: 󰒍 # Default = 󰒍
  .asoundrc:  # Default = 
  .atom:  # Default = 
  .ash:  # Default = 
  .ash_history:  # Default = 
  authorized_keys:  # Default = 
  assets:  # Default = 
  .android:  # Default = 
  .audacity:  # Default = 
  backups: 󰁯 # Default = 󰁯
  .bash_history: 󱆃 # Default = 󱆃
  .bash_logout: 󱆃 # Default = 󱆃
  .bash_profile: 󱆃 # Default = 󱆃
  .bashrc: 󱆃 # Default = 󱆃
  bin:  # Default = 
  .bpython_history:  # Default = 
  build:  # Default = 
  bspwmrc:  # Default = 
  .cache: 󰃨 # Default = 󰃨
  cache: 󰃨 # Default = 󰃨
  cargo:  # Default = 
  .cargo:  # Default = 
  .ccls: 󰃨 # Default = 󰃨
  changelog:  # Default = 
  .clang:  # Default = 
  composer:  # Default = 
  conf:  # Default = 
  config:  # Default = 
  configure:  # Default = 
  containerfile:  # Default = 
  content:  # Default = 
  contributing:  # Default = 
  copyright:  # Default = 
  cron:  # Default = 
  crontab:  # Default = 
  crypttab:  # Default = 
  .cshrc: 󱆃 # Default = 󱆃
  csh: 󱆃 # Default = 󱆃
  css:  # Default = 
  custom:  # Default = 
  .dbus:  # Default = 
  desktop:  # Default = 
  docker:  # Default = 
  dockerfile:  # Default = 
  doc:  # Default = 
  dist:  # Default = 
  documents:  # Default = 
  .doom:  # Default = 
  downloads: 󰉍 # Default = 󰉍
  .ds_store:  # Default = 
  .editorconfig:  # Default = 
  .electron:  # Default = 
  .emacs:  # Default = 
  .env:  # Default = 
  environment:  # Default = 
  .eslintrc:  # Default = 
  etc:  # Default = 
  favicon:  # Default = 
  favicons:  # Default = 
  .fennelrc:  # Default = 
  fstab:  # Default = 
  .fastboot:  # Default = 
  .gitattributes:  # Default = 
  # .gitconfig:                # Default = 
  .gitcredentials:  # Default = 
  .github:  # Default = 
  gitignore_global:  # Default = 
  .gitignore:  # Default = 
  .gitlab:  # Default = 
  .gitmodules:  # Default = 
  .git:  # Default = 
  .gnupg: 󰢬 # Default = 󰢬
  go:  # Default = 
  gradle:  # Default = 
  gradlew:  # Default = 
  group:  # Default = 
  gruntfile:  # Default = 
  gshadow:  # Default = 
  gulpfile:  # Default = 
  heroku:  # Default = 
  hidden:  # Default = 
  home:  # Default = 
  hostname:  # Default = 
  hosts: 󰀂 # Default = 󰀂
  .htaccess:  # Default = 
  htoprc:  # Default = 
  .htpasswd:  # Default = 
  .icons:  # Default = 
  icons:  # Default = 
  id_dsa: 󰷖 # Default = 󰷖
  id_ecdsa: 󰷖 # Default = 󰷖
  id_rsa: 󰷖 # Default = 󰷖
  .idlerc:  # Default = 
  img:  # Default = 
  include:  # Default = 
  init:  # Default = 
  .inputrc:  # Default = 
  inputrc:  # Default = 
  .java:  # Default = 
  jenkinsfile:  # Default = 
  js:  # Default = 
  jule:  # Default = 
  .jupyter:  # Default = 
  kbuild:  # Default = 
  kconfig:  # Default = 
  kdeglobals:  # Default = 
  kdenliverc:  # Default = 
  known_hosts:  # Default = 
  .kshrc:  # Default = 
  libexec:  # Default = 
  lib32:  # Default = 
  lib64:  # Default = 
  lib:  # Default = 
  license:  # Default = 
  licenses:  # Default = 
  localized:  # Default = 
  lsb:  # Default = 
  .lynxrc:  # Default = 
  .mailcap: 󰇰 # Default = 󰇰
  mail: 󰇰 # Default = 󰇰
  magic:  # Default = 
  maintainers:  # Default = 
  makefile:  # Default = 
  manifest:  # Default = 
  md5sum: 󰕥 # Default = 󰕥
  meson:  # Default = 
  metadata:  # Default = 
  media:  # Default = 
  .mime: 󰙅 # Default = 󰙅
  mime: 󰙅 # Default = 󰙅
  module:  # Default = 
  .mozilla:  # Default = 
  music: 󱍙 # Default = 󱍙
  muttrc:  # Default = 
  .muttrc:  # Default = 
  .mutt:  # Default = 
  .mypy_cache: 󰃨 # Default = 󰃨
  neomuttrc:  # Default = 
  .neomuttrc:  # Default = 
  netlify:  # Default = 
  .nix:  # Default = 
  .node:  # Default = 
  node_modules:  # Default = 
  .node_repl_history:  # Default = 
  npmignore:  # Default = 
  .npm:  # Default = 
  nvim:  # Default = 
  obj:  # Default = 
  os:  # Default = 
  package:  # Default = 
  packages:  # Default = 
  pam: 󰢬 # Default = 󰢬
  passwd:  # Default = 
  pictures: 󰉏 # Default = 󰉏
  pkgbuild:  # Default = 
  .pki:  # Default = 
  portage:  # Default = 
  profile:  # Default = 
  .profile:  # Default = 
  public:  # Default = 
  __pycache__:  # Default = 
  pyproject:  # Default = 
  .python_history:  # Default = 
  .pypirc:  # Default = 
  rc:  # Default = 
  readme:  # Default = 
  .release:  # Default = 
  requirements: 󰌠 # Default = 󰌠
  robots: 󰚩 # Default = 󰚩
  root: 󰉐 # Default = 󰉐
  rubydoc:  # Default = 
  runtime: 󰌠 # Default = 󰌠
  .rustup:  # Default = 
  rustfmt:  # Default = 
  .rvm:  # Default = 
  sass:  # Default = 
  sbin:  # Default = 
  scripts:  # Default = 
  scss:  # Default = 
  sha256sum: 󰕥 # Default = 󰕥
  shadow:  # Default = 
  share:  # Default = 
  .shellcheckrc:  # Default = 
  shells:  # Default = 
  .spacemacs:  # Default = 
  .sqlite_history:  # Default = 
  src: 󱧼 # Default = 󱧼
  source: 󱧼 # Default = 󱧼
  .ssh: 󰢬 # Default = 󰢬
  static:  # Default = 
  std: 󰅱 # Default = 󰅱
  styles:  # Default = 
  subgid:  # Default = 
  subuid:  # Default = 
  sudoers:  # Default = 
  sxhkdrc:  # Default = 
  template:  # Default = 
  tests: 󰙨 # Default = 󰙨
  test: 󰙨 # Default = 󰙨
  tigrc:  # Default = 
  timezone:  # Default = 
  tox:  # Default = 
  .trash:  # Default = 
  ts:  # Default = 
  .tox:  # Default = 
  unlicense:  # Default = 
  url:  # Default = 
  user:  # Default = 
  vagrantfile:  # Default = 
  vendor: 󰫦 # Default = 󰫦
  venv: 󰌠 # Default = 󰌠
  videos:  # Default = 
  .viminfo:  # Default = 
  .vimrc:  # Default = 
  vimrc:  # Default = 
  .vim:  # Default = 
  vim:  # Default = 
  .vscode:  # Default = 
  webpack: 󰜫 # Default = 󰜫
  .wgetrc:  # Default = 
  wgetrc:  # Default = 
  .xauthority:  # Default = 
  .Xauthority:  # Default = 
  xbps:  # Default = 
  .xinitrc:  # Default = 
  .xmodmap:  # Default = 
  .Xmodmap:  # Default = 
  xmonad:  # Default = 
  xorg:  # Default = 
  .xprofile:  # Default = 
  .Xprofile:  # Default = 
  .xresources:  # Default = 
  .yarnrc:  # Default = 
  yarn:  # Default = 
  zathurarc:  # Default = 
  .zcompdump:  # Default = 
  .zlogin: 󱆃 # Default = 󱆃
  .zlogout: 󱆃 # Default = 󱆃
  .zprofile: 󱆃 # Default = 󱆃
  .zsh_history: 󱆃 # Default = 󱆃
  .zshrc: 󱆃 # Default = 󱆃

extension:
  1:  # Default = 
  2:  # Default = 
  3:  # Default = 
  4:  # Default = 
  5:  # Default = 
  6:  # Default = 
  7:  # Default = 
  7z:  # Default = 
  8:  # Default = 
  890: 󰅞 # Default = 󰅞
  a:  # Default = 
  ai:  # Default = 
  ape:  # Default = 
  apk:  # Default = 
  apng:  # Default = 
  ar:  # Default = 
  asc: 󰦝 # Default = 󰦝
  asm:  # Default = 
  asp:  # Default = 
  avi:  # Default = 
  avif:  # Default = 
  avro:  # Default = 
  awk:  # Default = 
  bak: 󰁯 # Default = 󰁯
  bash_history:  # Default = 
  bash_profile:  # Default = 
  bashrc:  # Default = 
  bash:  # Default = 
  bat:  # Default = 
  bin:  # Default = 
  bio: 󰐑 # Default = 󰐑
  blend: 󰂫 # Default = 󰂫
  blend1: 󰂫 # Default = 󰂫
  bmp:  # Default = 
  bz2:  # Default = 
  cc:  # Default = 
  cfg:  # Default = 
  cip: 󰅞 # Default = 󰅞
  cjs:  # Default = 
  class:  # Default = 
  cljs:  # Default = 
  clj:  # Default = 
  cls:  # Default = 
  cl: 󰅲 # Default = 󰅲
  cmd:  # Default = 
  coffee:  # Default = 
  conf:  # Default = 
  cpp:  # Default = 
  cp:  # Default = 
  cshtml:  # Default = 
  csh:  # Default = 
  csproj: 󰌛 # Default = 󰌛
  css:  # Default = 
  cs: 󰌛 # Default = 󰌛
  csv:  # Default = 
  csx: 󰌛 # Default = 󰌛
  cts:  # Default = 
  c:  # Default = 
  cue:  # Default = 
  cxx:  # Default = 
  cypher:  # Default = 
  dart:  # Default = 
  dat:  # Default = 
  db:  # Default = 
  deb:  # Default = 
  desktop:  # Default = 
  diff:  # Default = 
  dll:  # Default = 
  dockerfile:  # Default = 
  doc:  # Default = 
  docx:  # Default = 
  download:  # Default = 
  ds_store:  # Default = 
  dump:  # Default = 
  ebook:  # Default = 
  ebuild:  # Default = 
  eclass:  # Default = 
  editorconfig:  # Default = 
  egg:  # Default = 
  ejs:  # Default = 
  elc: 󰅲 # Default = 󰅲
  elf:  # Default = 
  elm:  # Default = 
  el: 󰅲 # Default = 󰅲
  env:  # Default = 
  eot:  # Default = 
  epub:  # Default = 
  erb:  # Default = 
  erl:  # Default = 
  exe:  # Default = 
  exs:  # Default = 
  ex:  # Default = 
  fish:  # Default = 
  flac:  # Default = 
  flv:  # Default = 
  fnl:  # Default = 
  font:  # Default = 
  fpl: 󰐑 # Default = 󰐑
  fsi:  # Default = 
  fs:  # Default = 
  fsx:  # Default = 
  gdoc:  # Default = 
  gemfile:  # Default = 
  gemspec:  # Default = 
  gform:  # Default = 
  gif:  # Default = 
  git:  # Default = 
  go:  # Default = 
  gpg: 󰦝 # Default = 󰦝
  gradle:  # Default = 
  gsheet:  # Default = 
  gslides:  # Default = 
  guardfile:  # Default = 
  gv: 󱁉 # Default = 󱁉
  gz:  # Default = 
  hbs:  # Default = 
  heic:  # Default = 
  heif:  # Default = 
  heix:  # Default = 
  hh:  # Default = 
  hpp:  # Default = 
  hs:  # Default = 
  html:  # Default = 
  htm:  # Default = 
  h:  # Default = 
  hxx:  # Default = 
  ico:  # Default = 
  image:  # Default = 
  img:  # Default = 
  iml:  # Default = 
  info:  # Default = 
  in:  # Default = 
  ini:  # Default = 
  ipynb:  # Default = 
  iso:  # Default = 
  j2:  # Default = 
  jar:  # Default = 
  java:  # Default = 
  jinja:  # Default = 
  jl:  # Default = 
  jpeg:  # Default = 
  jpg:  # Default = 
  jsonc:  # Default = 
  json:  # Default = 
  js:  # Default = 
  jsx:  # Default = 
  jule:  # Default = 
  key: 󰌆 # Default = 󰌆
  ksh:  # Default = 
  kt:  # Default = 
  kts:  # Default = 
  kusto:  # Default = 
  ldb:  # Default = 
  ld:  # Default = 
  less:  # Default = 
  lhs:  # Default = 
  license:  # Default = 
  lisp: 󰅲 # Default = 󰅲
  list:  # Default = 
  localized:  # Default = 
  lock:  # Default = 
  log:  # Default = 
  lss:  # Default = 
  lua:  # Default = 
  lz:  # Default = 
  mgc:  # Default = 
  m3u8: 󰐑 # Default = 󰐑
  m3u: 󰐑 # Default = 󰐑
  m4:  # Default = 
  m4a:  # Default = 
  m4v:  # Default = 
  magnet:  # Default = 
  make:  # Default = 
  makefile:  # Default = 
  malloy:  # Default = 
  man:  # Default = 
  markdown:  # Default = 
  md:  # Default = 
  mjs:  # Default = 
  mkd:  # Default = 
  mk:  # Default = 
  mkv:  # Default = 
  ml:  # Default = 
  mli:  # Default = 
  mll:  # Default = 
  mly:  # Default = 
  mobi:  # Default = 
  mov:  # Default = 
  mp3:  # Default = 
  mp4:  # Default = 
  msi:  # Default = 
  mts:  # Default = 
  mustache:  # Default = 
  nim:  # Default = 
  nimble:  # Default = 
  nix:  # Default = 
  npmignore:  # Default = 
  odp:  # Default = 
  ods:  # Default = 
  odt:  # Default = 
  ogg:  # Default = 
  ogv:  # Default = 
  old: 󰁯 # Default = 󰁯
  opus:  # Default = 
  orig: 󰁯 # Default = 󰁯
  org:  # Default = 
  otf:  # Default = 
  o:  # Default = 
  part:  # Default = 
  patch:  # Default = 
  pdb: 󰪪 # Default = 󰪪
  pdf:  # Default = 
  pem: 󰌆 # Default = 󰌆
  phar:  # Default = 
  php:  # Default = 
  pkg:  # Default = 
  pl:  # Default = 
  plist:  # Default = 
  pls: 󰐑 # Default = 󰐑
  plx:  # Default = 
  pm:  # Default = 
  png:  # Default = 
  pod:  # Default = 
  pp:  # Default = 
  ppt:  # Default = 
  pptx:  # Default = 
  procfile:  # Default = 
  properties:  # Default = 
  prql:  # Default = 
  ps1:  # Default = 
  psd:  # Default = 
  pub: 󰌆 # Default = 󰌆
  pug:  # Default = 
  sbv: 󰅞 # Default = 󰅞
  scc: 󰅞 # Default = 󰅞
  slt: 󰈡 # Default = 󰈡
  smi: 󰅞 # Default = 󰅞
  pxm:  # Default = 
  pyc:  # Default = 
  py:  # Default = 
  rakefile:  # Default = 
  rar:  # Default = 
  razor:  # Default = 
  rb:  # Default = 
  rdata: 󰟔 # Default = 󰟔
  rdb:  # Default = 
  rdoc:  # Default = 
  rds: 󰟔 # Default = 󰟔
  readme:  # Default = 
  rlib:  # Default = 
  rl:  # Default = 
  rmd:  # Default = 
  rmeta:  # Default = 
  rpm:  # Default = 
  rproj: 󰗆 # Default = 󰗆
  rq:  # Default = 
  rspec_parallel:  # Default = 
  rspec_status:  # Default = 
  rspec:  # Default = 
  rss:  # Default = 
  rs:  # Default = 
  rtf:  # Default = 
  rubydoc:  # Default = 
  r: 󰟔 # Default = 󰟔
  ru:  # Default = 
  sass:  # Default = 
  scala:  # Default = 
  scpt:  # Default = 
  scss:  # Default = 
  shell:  # Default = 
  sh:  # Default = 
  sig:  # Default = 
  slim:  # Default = 
  sln:  # Default = 
  so:  # Default = 
  sqlite3:  # Default = 
  sql:  # Default = 
  srt: 󰨖 # Default = 󰨖
  styl:  # Default = 
  stylus:  # Default = 
  sublime:  # Default = 
  sub: 󰨖 # Default = 󰨖
  s:  # Default = 
  svg:  # Default = 
  svelte:  # Default = 
  swift:  # Default = 
  swp:  # Default = 
  sym:  # Default = 
  tar:  # Default = 
  taz:  # Default = 
  tbz:  # Default = 
  tbz2:  # Default = 
  tex:  # Default = 
  tgz:  # Default = 
  tiff:  # Default = 
  timestamp:  # Default = 
  toml:  # Default = 
  torrent: 󰒍 # Default = 󰒍
  trash:  # Default = 
  ts:  # Default = 
  tsx:  # Default = 
  ttc:  # Default = 
  ttf:  # Default = 
  t:  # Default = 
  twig:  # Default = 
  txt:  # Default = 
  unity:  # Default = 
  unity32:  # Default = 
  video:  # Default = 
  vim:  # Default = 
  vlc: 󰐑 # Default = 󰐑
  vtt: 󰅞 # Default = 󰅞
  vue: 󰡄 # Default = 󰡄
  wav:  # Default = 
  webm:  # Default = 
  webp:  # Default = 
  whl:  # Default = 
  windows:  # Default = 
  wma:  # Default = 
  wmv:  # Default = 
  woff2:  # Default = 
  woff:  # Default = 
  wpl: 󰐑 # Default = 󰐑
  xbps:  # Default = 
  xcf:  # Default = 
  xls:  # Default = 
  xlsx:  # Default = 
  xml:  # Default = 
  xul:  # Default = 
  xz:  # Default = 
  yaml:  # Default = 
  yml:  # Default = 
  zip:  # Default = 
  zig:  # Default = 
  zon:  # Default = 
  zshrc:  # Default = 
  zsh:  # Default = 
  zst:  # Default = 

