[editor_open]
command = "nvim --server $NVIM --remote-send '<cmd>lua EditLineFromScooter(\"%file\", %line)<CR>'"

[preview]
# syntax_highlighting_theme = "TwoDark"
syntax_highlighting_theme = "Visual Studio Dark+"

# Built-in
# syntax_highlighting_theme = "base16-eighties.dark" # Default
# syntax_highlighting_theme = "base16-ocean.dark"

[style]
true_color = true
