[editor_open]
  command = "nvim --server $NVIM --remote-send '<cmd>lua EditLineFromScooter(\"%file\", %line)<CR>'"

[preview]
  # Built-in
  # syntax_highlighting_theme = "base16-eighties.dark" # Default
  # syntax_highlighting_theme = "base16-ocean.dark"

  syntax_highlighting_theme = "Catppuccin Mocha"

[style]
  true_color = true
